/**
 * Snippet Attribution & Embed Utilities
 *
 * Appends clean, developer-standard attribution headers to copied code snippets
 * and generates iframe embed codes to drive organic backlinks and viral distribution.
 */

export interface SnippetAttributionOptions {
  slug: string;
  platformSlug?: string;
  language?: "html" | "nextjs" | "helmet" | "javascript" | "typescript" | "liquid" | "plaintext" | string;
  withAttribution?: boolean;
}

/**
 * Returns the exact canonical URL for a tool or platform permutation
 */
export function getToolCanonicalUrl(slug: string, platformSlug?: string): string {
  if (platformSlug) {
    return `https://omniseotools.com/tools/${slug}/${platformSlug}`;
  }
  return `https://omniseotools.com/tools/${slug}`;
}

/**
 * Formats a code snippet with a language-appropriate attribution header.
 */
export function formatSnippetWithAttribution(
  code: string,
  options: SnippetAttributionOptions
): string {
  if (options.withAttribution === false) {
    return code;
  }

  const url = getToolCanonicalUrl(options.slug, options.platformSlug);
  const lang = (options.language || "html").toLowerCase();

  let header = `<!-- Generated by OmniSEO Tools (${url}) -->\n`;

  if (
    lang === "nextjs" ||
    lang === "javascript" ||
    lang === "typescript" ||
    lang === "helmet" ||
    lang === "jsx" ||
    lang === "tsx" ||
    lang === "ts" ||
    lang === "js"
  ) {
    header = `// Generated by OmniSEO Tools (${url})\n`;
  } else if (lang === "liquid") {
    header = `{% comment %} Generated by OmniSEO Tools (${url}) {% endcomment %}\n`;
  } else if (lang === "python" || lang === "py" || lang === "bash" || lang === "sh") {
    header = `# Generated by OmniSEO Tools (${url})\n`;
  }

  // Prevent duplicate attribution if already present
  if (code.startsWith(header.trim()) || code.includes("Generated by OmniSEO Tools")) {
    return code;
  }

  return `${header}${code}`;
}

/**
 * Generates ready-to-copy responsive iframe embed markup.
 */
export function getEmbedIframeSnippet(
  slug: string,
  toolName: string,
  height: number = 600
): string {
  const canonicalUrl = `https://omniseotools.com/tools/${slug}`;
  const embedUrl = `https://omniseotools.com/embed/${slug}`;

  return `<iframe src="${embedUrl}" width="100%" height="${height}" frameborder="0" title="OmniSEO Tools - ${toolName}"></iframe>\n<p style="font-size:12px;color:#64748b;">Free utility powered by <a href="${canonicalUrl}" target="_blank" rel="noopener">OmniSEO Tools</a></p>`;
}
