"use client";

import React, { useState, useMemo } from "react";
import { 
  Sparkles, 
  Copy, 
  Check, 
  Download, 
  RotateCcw, 
  ShieldAlert, 
  CheckCircle2, 
  AlertTriangle,
  Plus,
  Trash2,
  Bot,
  Search,
  Sliders,
  CheckCircle,
  XCircle,
  FileCode
} from "lucide-react";
import { cn } from "@/lib/utils";

const PRESETS = [
  {
    name: "Standard SEO (Allow All)",
    defaultPolicy: "allow" as const,
    disallowedPaths: ["/admin/", "/api/", "/login/"],
    allowedPaths: [] as string[],
    aiScrapers: "allow" as const,
    sitemaps: ["https://example.com/sitemap.xml"],
    crawlDelay: "",
  },
  {
    name: "Block AI Scrapers",
    defaultPolicy: "allow" as const,
    disallowedPaths: ["/admin/", "/api/"],
    allowedPaths: [] as string[],
    aiScrapers: "block" as const,
    sitemaps: ["https://example.com/sitemap.xml"],
    crawlDelay: "",
  },
  {
    name: "WordPress Standard",
    defaultPolicy: "allow" as const,
    disallowedPaths: ["/wp-admin/"],
    allowedPaths: ["/wp-admin/admin-ajax.php"],
    aiScrapers: "allow" as const,
    sitemaps: ["https://example.com/sitemap_index.xml"],
    crawlDelay: "",
  },
  {
    name: "E-Commerce Store",
    defaultPolicy: "allow" as const,
    disallowedPaths: ["/cart/", "/checkout/", "/account/", "/search?*", "/*?sort="],
    allowedPaths: [] as string[],
    aiScrapers: "allow" as const,
    sitemaps: ["https://example.com/sitemap.xml"],
    crawlDelay: "",
  },
  {
    name: "Staging Lock (Disallow All)",
    defaultPolicy: "disallow" as const,
    disallowedPaths: ["/"],
    allowedPaths: [] as string[],
    aiScrapers: "block" as const,
    sitemaps: [] as string[],
    crawlDelay: "",
  },
];

const COMMON_DISALLOW_SUGGESTIONS = [
  "/admin/",
  "/api/",
  "/private/",
  "/checkout/",
  "/cart/",
  "/login/",
  "/tmp/",
  "/*?*",
];

export function RobotsTxtGeneratorTool() {
  const [defaultPolicy, setDefaultPolicy] = useState<"allow" | "disallow">("allow");
  const [disallowedPaths, setDisallowedPaths] = useState<string[]>(["/admin/", "/api/"]);
  const [allowedPaths, setAllowedPaths] = useState<string[]>([]);
  const [newDisallow, setNewDisallow] = useState("");
  const [newAllow, setNewAllow] = useState("");
  const [sitemaps, setSitemaps] = useState<string[]>(["https://omniseotools.com/sitemap.xml"]);
  const [newSitemap, setNewSitemap] = useState("");
  const [crawlDelay, setCrawlDelay] = useState("");
  
  // AI Bot Toggles
  const [blockGptBot, setBlockGptBot] = useState(false);
  const [blockClaudeBot, setBlockClaudeBot] = useState(false);
  const [blockCcBot, setBlockCcBot] = useState(false);
  const [blockGoogleExtended, setBlockGoogleExtended] = useState(false);
  const [blockPerplexity, setBlockPerplexity] = useState(false);

  // Path Tester state
  const [testPath, setTestPath] = useState("/admin/settings");
  const [copied, setCopied] = useState(false);

  // Generate output text
  const generatedRobotsTxt = useMemo(() => {
    const lines: string[] = [];

    lines.push("# robots.txt generated by OmniSEOTools (https://omniseotools.com)");
    lines.push("# Standard Search Engine Crawler Rules");
    lines.push("User-agent: *");

    if (defaultPolicy === "disallow" && disallowedPaths.includes("/")) {
      lines.push("Disallow: /");
    } else {
      if (disallowedPaths.length === 0) {
        lines.push("Disallow:");
      } else {
        disallowedPaths.forEach((p) => {
          if (p.trim()) lines.push(`Disallow: ${p.trim()}`);
        });
      }
      allowedPaths.forEach((p) => {
        if (p.trim()) lines.push(`Allow: ${p.trim()}`);
      });
    }

    if (crawlDelay.trim() && !isNaN(Number(crawlDelay))) {
      lines.push(`Crawl-delay: ${crawlDelay.trim()}`);
    }

    // Specific AI Scrapers
    const aiBots: { name: string; blocked: boolean }[] = [
      { name: "GPTBot", blocked: blockGptBot },
      { name: "ClaudeBot", blocked: blockClaudeBot },
      { name: "Claude-Web", blocked: blockClaudeBot },
      { name: "CCBot", blocked: blockCcBot },
      { name: "Google-Extended", blocked: blockGoogleExtended },
      { name: "PerplexityBot", blocked: blockPerplexity },
    ];

    const blockedAiBots = aiBots.filter((b) => b.blocked);
    if (blockedAiBots.length > 0) {
      lines.push("");
      lines.push("# AI Crawler & Dataset Training Directives");
      blockedAiBots.forEach((bot) => {
        lines.push(`User-agent: ${bot.name}`);
        lines.push("Disallow: /");
        lines.push("");
      });
    }

    // Sitemaps
    if (sitemaps.length > 0) {
      lines.push("");
      lines.push("# XML Sitemaps");
      sitemaps.forEach((s) => {
        if (s.trim()) lines.push(`Sitemap: ${s.trim()}`);
      });
    }

    return lines.join("\n");
  }, [
    defaultPolicy,
    disallowedPaths,
    allowedPaths,
    crawlDelay,
    blockGptBot,
    blockClaudeBot,
    blockCcBot,
    blockGoogleExtended,
    blockPerplexity,
    sitemaps,
  ]);

  // Path Tester evaluation
  const testResult = useMemo(() => {
    if (!testPath) return { allowed: true, reason: "No path provided" };
    const normalized = testPath.startsWith("/") ? testPath : "/" + testPath;

    // Check if entire site is blocked
    if (disallowedPaths.includes("/")) {
      return { allowed: false, reason: "Entire site is blocked (Disallow: /)" };
    }

    // Check allow rules first (more specific)
    for (const allow of allowedPaths) {
      if (allow && normalized.startsWith(allow)) {
        return { allowed: true, reason: `Matched specific rule: Allow ${allow}` };
      }
    }

    // Check disallow rules
    for (const disallow of disallowedPaths) {
      if (disallow && normalized.startsWith(disallow)) {
        return { allowed: false, reason: `Matched rule: Disallow ${disallow}` };
      }
    }

    return { allowed: true, reason: "No matching disallow rule (Permitted by default)" };
  }, [testPath, disallowedPaths, allowedPaths]);

  const handleAddDisallow = (pathToAdd?: string) => {
    const val = pathToAdd || newDisallow.trim();
    if (val && !disallowedPaths.includes(val)) {
      setDisallowedPaths([...disallowedPaths, val]);
      if (!pathToAdd) setNewDisallow("");
    }
  };

  const handleRemoveDisallow = (p: string) => {
    setDisallowedPaths(disallowedPaths.filter((item) => item !== p));
  };

  const handleAddAllow = () => {
    if (newAllow.trim() && !allowedPaths.includes(newAllow.trim())) {
      setAllowedPaths([...allowedPaths, newAllow.trim()]);
      setNewAllow("");
    }
  };

  const handleRemoveAllow = (p: string) => {
    setAllowedPaths(allowedPaths.filter((item) => item !== p));
  };

  const handleAddSitemap = () => {
    if (newSitemap.trim() && !sitemaps.includes(newSitemap.trim())) {
      setSitemaps([...sitemaps, newSitemap.trim()]);
      setNewSitemap("");
    }
  };

  const handleRemoveSitemap = (s: string) => {
    setSitemaps(sitemaps.filter((item) => item !== s));
  };

  const handleApplyPreset = (preset: typeof PRESETS[0]) => {
    setDefaultPolicy(preset.defaultPolicy);
    setDisallowedPaths(preset.disallowedPaths);
    setAllowedPaths(preset.allowedPaths);
    setSitemaps(preset.sitemaps);
    setCrawlDelay(preset.crawlDelay);
    if (preset.aiScrapers === "block") {
      setBlockGptBot(true);
      setBlockClaudeBot(true);
      setBlockCcBot(true);
      setBlockGoogleExtended(true);
      setBlockPerplexity(true);
    } else {
      setBlockGptBot(false);
      setBlockClaudeBot(false);
      setBlockCcBot(false);
      setBlockGoogleExtended(false);
      setBlockPerplexity(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedRobotsTxt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([generatedRobotsTxt], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "robots.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="space-y-8">
      
      {/* Top Presets Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200/80 dark:border-slate-800/80 bg-white dark:bg-slate-900/60 p-4 shadow-sm">
        <div className="flex items-center gap-2 overflow-x-auto pb-1 sm:pb-0">
          <span className="text-xs font-semibold text-slate-500 flex items-center gap-1.5 shrink-0">
            <Sparkles className="h-3.5 w-3.5 text-emerald-500" /> Presets:
          </span>
          {PRESETS.map((p) => (
            <button
              key={p.name}
              onClick={() => handleApplyPreset(p)}
              className="rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50 px-2.5 py-1 text-xs font-medium text-slate-700 dark:text-slate-300 hover:border-emerald-500 dark:hover:border-emerald-500 transition-colors whitespace-nowrap"
            >
              {p.name}
            </button>
          ))}
        </div>

        <button
          onClick={() => handleApplyPreset(PRESETS[0])}
          className="flex items-center gap-1 text-xs text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 px-2 py-1 rounded-md"
        >
          <RotateCcw className="h-3.5 w-3.5" />
          <span>Reset</span>
        </button>
      </div>

      {/* Disallow All Warning Banner */}
      {disallowedPaths.includes("/") && (
        <div className="flex items-center gap-3 rounded-2xl border border-rose-500/30 bg-rose-50 dark:bg-rose-950/40 p-4 text-xs text-rose-800 dark:text-rose-200">
          <AlertTriangle className="h-5 w-5 text-rose-600 shrink-0" />
          <div>
            <strong className="font-semibold block">Warning: Entire Website is Blocked!</strong>
            <span><code>Disallow: /</code> blocks all search engines from indexing your site. Only use this for staging/dev environments.</span>
          </div>
        </div>
      )}

      {/* 2-Column Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Left Column: Directives Configuration (6 cols) */}
        <div className="lg:col-span-6 space-y-6 rounded-3xl border border-slate-200/80 dark:border-slate-800/80 bg-white dark:bg-slate-900/60 p-6 shadow-sm">
          
          <h2 className="text-base font-bold text-slate-900 dark:text-white flex items-center justify-between">
            <span>Directives & Rule Builder</span>
            <span className="text-xs font-normal text-slate-500">Universal REP Protocol</span>
          </h2>

          {/* Disallowed Paths Manager */}
          <div className="space-y-3">
            <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 flex items-center justify-between">
              <span>Disallowed Paths (<code>Disallow</code>)</span>
              <span className="text-[11px] text-slate-400 font-normal">{disallowedPaths.length} rules</span>
            </label>

            {/* Quick add suggestion chips */}
            <div className="flex flex-wrap gap-1.5 text-[11px]">
              <span className="text-slate-400 text-[10px] self-center mr-1">Quick add:</span>
              {COMMON_DISALLOW_SUGGESTIONS.map((chip) => (
                <button
                  key={chip}
                  type="button"
                  onClick={() => handleAddDisallow(chip)}
                  className="rounded-md border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/60 px-2 py-0.5 text-slate-600 dark:text-slate-300 hover:border-emerald-500 font-mono text-[10px]"
                >
                  +{chip}
                </button>
              ))}
            </div>

            {/* Add Custom Disallow Input */}
            <div className="flex gap-2">
              <input
                type="text"
                value={newDisallow}
                onChange={(e) => setNewDisallow(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleAddDisallow()}
                placeholder="e.g., /admin/ or /private/"
                className="flex-1 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 p-2.5 text-xs text-slate-900 dark:text-slate-100 font-mono focus:border-emerald-500 focus:outline-none"
              />
              <button
                type="button"
                onClick={() => handleAddDisallow()}
                className="flex items-center gap-1 rounded-xl bg-slate-900 dark:bg-slate-800 hover:bg-slate-800 px-3.5 py-2 text-xs font-semibold text-white shadow-sm transition-colors"
              >
                <Plus className="h-3.5 w-3.5" />
                <span>Add</span>
              </button>
            </div>

            {/* Active Disallow Rules List */}
            <div className="flex flex-wrap gap-2 max-h-36 overflow-y-auto pt-1">
              {disallowedPaths.map((p) => (
                <span
                  key={p}
                  className="inline-flex items-center gap-1.5 rounded-lg border border-rose-500/20 bg-rose-50 dark:bg-rose-950/40 px-2.5 py-1 text-xs font-mono text-rose-700 dark:text-rose-300"
                >
                  <span>Disallow: {p}</span>
                  <button
                    onClick={() => handleRemoveDisallow(p)}
                    className="text-rose-500 hover:text-rose-700 ml-1"
                  >
                    <Trash2 className="h-3 w-3" />
                  </button>
                </span>
              ))}
            </div>
          </div>

          {/* Allowed Paths (Exceptions) */}
          <div className="space-y-3 pt-3 border-t border-slate-100 dark:border-slate-800">
            <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 flex items-center justify-between">
              <span>Allowed Exceptions (<code>Allow</code>)</span>
              <span className="text-[11px] text-slate-400 font-normal">{allowedPaths.length} rules</span>
            </label>

            <div className="flex gap-2">
              <input
                type="text"
                value={newAllow}
                onChange={(e) => setNewAllow(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleAddAllow()}
                placeholder="e.g., /wp-admin/admin-ajax.php"
                className="flex-1 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 p-2.5 text-xs text-slate-900 dark:text-slate-100 font-mono focus:border-emerald-500 focus:outline-none"
              />
              <button
                type="button"
                onClick={handleAddAllow}
                className="flex items-center gap-1 rounded-xl bg-slate-900 dark:bg-slate-800 hover:bg-slate-800 px-3.5 py-2 text-xs font-semibold text-white shadow-sm transition-colors"
              >
                <Plus className="h-3.5 w-3.5" />
                <span>Add</span>
              </button>
            </div>

            {allowedPaths.length > 0 && (
              <div className="flex flex-wrap gap-2">
                {allowedPaths.map((p) => (
                  <span
                    key={p}
                    className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-500/20 bg-emerald-50 dark:bg-emerald-950/40 px-2.5 py-1 text-xs font-mono text-emerald-700 dark:text-emerald-300"
                  >
                    <span>Allow: {p}</span>
                    <button onClick={() => handleRemoveAllow(p)} className="text-emerald-500 hover:text-emerald-700 ml-1">
                      <Trash2 className="h-3 w-3" />
                    </button>
                  </span>
                ))}
              </div>
            )}
          </div>

          {/* AI Crawler & Scraper Toggles */}
          <div className="space-y-3 pt-3 border-t border-slate-100 dark:border-slate-800">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1.5">
                <Bot className="h-4 w-4 text-emerald-600" />
                <span className="text-xs font-semibold text-slate-900 dark:text-white">
                  Block AI Dataset Training Scrapers
                </span>
              </div>
              <span className="text-[10px] text-slate-400">Opt-out Toggles</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
              <label className="flex items-center gap-2 p-2 rounded-xl border border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/40 cursor-pointer">
                <input
                  type="checkbox"
                  checked={blockGptBot}
                  onChange={(e) => setBlockGptBot(e.target.checked)}
                  className="rounded text-emerald-600 focus:ring-emerald-500"
                />
                <span>Block OpenAI (GPTBot)</span>
              </label>

              <label className="flex items-center gap-2 p-2 rounded-xl border border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/40 cursor-pointer">
                <input
                  type="checkbox"
                  checked={blockClaudeBot}
                  onChange={(e) => setBlockClaudeBot(e.target.checked)}
                  className="rounded text-emerald-600 focus:ring-emerald-500"
                />
                <span>Block Anthropic (ClaudeBot)</span>
              </label>

              <label className="flex items-center gap-2 p-2 rounded-xl border border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/40 cursor-pointer">
                <input
                  type="checkbox"
                  checked={blockCcBot}
                  onChange={(e) => setBlockCcBot(e.target.checked)}
                  className="rounded text-emerald-600 focus:ring-emerald-500"
                />
                <span>Block Common Crawl (CCBot)</span>
              </label>

              <label className="flex items-center gap-2 p-2 rounded-xl border border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/40 cursor-pointer">
                <input
                  type="checkbox"
                  checked={blockGoogleExtended}
                  onChange={(e) => setBlockGoogleExtended(e.target.checked)}
                  className="rounded text-emerald-600 focus:ring-emerald-500"
                />
                <span>Block Google-Extended (Gemini)</span>
              </label>
            </div>
          </div>

          {/* XML Sitemaps */}
          <div className="space-y-3 pt-3 border-t border-slate-100 dark:border-slate-800">
            <label className="text-xs font-semibold text-slate-700 dark:text-slate-300">
              XML Sitemaps (<code>Sitemap:</code>)
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                value={newSitemap}
                onChange={(e) => setNewSitemap(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleAddSitemap()}
                placeholder="https://example.com/sitemap.xml"
                className="flex-1 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 p-2.5 text-xs text-slate-900 dark:text-slate-100 font-mono focus:border-emerald-500 focus:outline-none"
              />
              <button
                type="button"
                onClick={handleAddSitemap}
                className="flex items-center gap-1 rounded-xl bg-slate-900 dark:bg-slate-800 hover:bg-slate-800 px-3.5 py-2 text-xs font-semibold text-white shadow-sm transition-colors"
              >
                <Plus className="h-3.5 w-3.5" />
                <span>Add</span>
              </button>
            </div>

            {sitemaps.map((s) => (
              <div key={s} className="flex items-center justify-between p-2 rounded-lg bg-slate-50 dark:bg-slate-800/50 text-xs font-mono text-slate-700 dark:text-slate-300">
                <span className="truncate max-w-[340px]">{s}</span>
                <button onClick={() => handleRemoveSitemap(s)} className="text-slate-400 hover:text-rose-500">
                  <Trash2 className="h-3.5 w-3.5" />
                </button>
              </div>
            ))}
          </div>

        </div>

        {/* Right Column: Live Robots.txt Canvas & Path Tester (6 cols) */}
        <div className="lg:col-span-6 space-y-6">
          
          {/* Live Code Preview */}
          <div className="rounded-3xl border border-slate-200/80 dark:border-slate-800/80 bg-white dark:bg-slate-900/60 p-6 shadow-sm">
            
            <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-4 mb-4">
              <div className="flex items-center gap-2">
                <FileCode className="h-4 w-4 text-emerald-600" />
                <span className="text-sm font-bold text-slate-900 dark:text-white">
                  Generated robots.txt
                </span>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-3 py-1.5 text-xs font-semibold text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"
                >
                  {copied ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
                  <span>{copied ? "Copied!" : "Copy"}</span>
                </button>

                <button
                  onClick={handleDownload}
                  className="flex items-center gap-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 px-3 py-1.5 text-xs font-semibold text-white shadow-sm transition-colors"
                >
                  <Download className="h-3.5 w-3.5" />
                  <span>Download .txt</span>
                </button>
              </div>
            </div>

            {/* Mono Code Block */}
            <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-950 p-4 text-xs font-mono text-emerald-400 overflow-x-auto shadow-inner min-h-[300px] leading-relaxed">
              <pre className="whitespace-pre">{generatedRobotsTxt}</pre>
            </div>

          </div>

          {/* Interactive URL Path Tester */}
          <div className="rounded-3xl border border-slate-200/80 dark:border-slate-800/80 bg-white dark:bg-slate-900/60 p-6 shadow-sm space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                  URL Path Access Validator
                </h3>
                <p className="text-xs text-slate-500">Test if a URL path is allowed or blocked by your rules</p>
              </div>
              <span className="text-[11px] font-mono text-emerald-600 font-semibold">
                Simulator
              </span>
            </div>

            <div className="space-y-2">
              <input
                type="text"
                value={testPath}
                onChange={(e) => setTestPath(e.target.value)}
                placeholder="e.g., /admin/dashboard or /blog/post-1"
                className="w-full rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 p-2.5 text-xs text-slate-900 dark:text-slate-100 font-mono focus:border-emerald-500 focus:outline-none"
              />

              {/* Status Outcome */}
              <div
                className={cn(
                  "flex items-center justify-between p-3 rounded-xl text-xs font-medium border",
                  testResult.allowed
                    ? "bg-emerald-50 dark:bg-emerald-950/40 border-emerald-500/30 text-emerald-800 dark:text-emerald-200"
                    : "bg-rose-50 dark:bg-rose-950/40 border-rose-500/30 text-rose-800 dark:text-rose-200"
                )}
              >
                <div className="flex items-center gap-2">
                  {testResult.allowed ? (
                    <CheckCircle className="h-4 w-4 text-emerald-600 shrink-0" />
                  ) : (
                    <XCircle className="h-4 w-4 text-rose-600 shrink-0" />
                  )}
                  <span>Status: <strong>{testResult.allowed ? "ALLOWED (200 OK)" : "BLOCKED (Disallowed)"}</strong></span>
                </div>
                <span className="text-[11px] opacity-80">{testResult.reason}</span>
              </div>
            </div>

          </div>

        </div>

      </div>

    </div>
  );
}
