/**
 * Multi-Framework Syntax Formatter Utility
 *
 * Generates production-ready SEO & Open Graph meta tag code exports across
 * HTML5, Next.js App Router (TypeScript Metadata), and Shopify Liquid.
 */

import { getToolCanonicalUrl } from "@/lib/snippet-attribution";

export interface MetaFormData {
  title?: string;
  description?: string;
  url?: string;
  siteName?: string;
  image?: string;
  imageUrl?: string;
  ogType?: string;
  twitterCard?: string;
  twitterHandle?: string;
  robots?: string;
  slug?: string;
  platformSlug?: string;
}

export type FormatterOptions =
  | string
  | { withAttribution?: boolean; attributionUrl?: string }
  | undefined;

// Helper to escape HTML attributes
export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// Helper to safely escape TS string literals
export function escapeTs(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function resolveAttributionUrl(
  data: MetaFormData,
  options?: FormatterOptions
): string | null {
  if (typeof options === "string") {
    return options.trim() ? options : null;
  }
  if (typeof options === "object" && options !== null) {
    if (options.withAttribution === false) {
      return null;
    }
    if (options.attributionUrl) {
      return options.attributionUrl;
    }
  }
  if (
    options === undefined ||
    (typeof options === "object" && options?.withAttribution !== false)
  ) {
    return getToolCanonicalUrl(
      data.slug || "open-graph-meta-generator",
      data.platformSlug
    );
  }
  return null;
}

/**
 * Formats meta tags as clean, standard HTML5 markup without deprecated tags or syntax defects.
 */
export function toHtml(
  data: MetaFormData,
  attributionUrlOrOptions?: FormatterOptions
): string {
  const attributionUrl = resolveAttributionUrl(data, attributionUrlOrOptions);
  const title = data.title || "";
  const description = data.description || "";
  const url = data.url?.trim() || "";
  const image = (data.image || data.imageUrl || "").trim();
  const siteName = data.siteName || "";
  const robots = data.robots || "index, follow";

  const lines: string[] = [];

  if (attributionUrl) {
    lines.push(`<!-- Generated by OmniSEO Tools (${attributionUrl}) -->`);
  }

  lines.push(
    `<!-- Primary Meta Tags -->`,
    `<title>${escapeHtml(title)}</title>`,
    `<meta name="description" content="${escapeHtml(description)}" />`,
    `<meta name="robots" content="${escapeHtml(robots)}" />`
  );

  if (url) {
    lines.push(`<link rel="canonical" href="${escapeHtml(url)}" />`);
  }

  lines.push("", "<!-- Open Graph / Facebook -->");
  lines.push(`<meta property="og:type" content="website" />`);
  if (url) lines.push(`<meta property="og:url" content="${escapeHtml(url)}" />`);
  lines.push(`<meta property="og:title" content="${escapeHtml(title)}" />`);
  lines.push(`<meta property="og:description" content="${escapeHtml(description)}" />`);
  if (image) lines.push(`<meta property="og:image" content="${escapeHtml(image)}" />`);
  if (siteName) lines.push(`<meta property="og:site_name" content="${escapeHtml(siteName)}" />`);

  lines.push("", "<!-- Twitter / X -->");
  lines.push(`<meta name="twitter:card" content="summary_large_image" />`);
  if (url) lines.push(`<meta name="twitter:url" content="${escapeHtml(url)}" />`);
  lines.push(`<meta name="twitter:title" content="${escapeHtml(title)}" />`);
  lines.push(`<meta name="twitter:description" content="${escapeHtml(description)}" />`);
  if (image) lines.push(`<meta name="twitter:image" content="${escapeHtml(image)}" />`);
  if (data.twitterHandle) {
    const handle = data.twitterHandle.startsWith("@")
      ? data.twitterHandle
      : `@${data.twitterHandle}`;
    lines.push(`<meta name="twitter:site" content="${escapeHtml(handle)}" />`);
    lines.push(`<meta name="twitter:creator" content="${escapeHtml(handle)}" />`);
  }

  return lines.join("\n");
}

/**
 * Formats meta tags into an idiomatic Next.js App Router TypeScript `Metadata` object.
 */
export function toNextJsMetadata(
  data: MetaFormData,
  attributionUrlOrOptions?: FormatterOptions
): string {
  const attributionUrl = resolveAttributionUrl(data, attributionUrlOrOptions);
  const title = data.title || "";
  const description = data.description || "";
  const url = data.url?.trim() || "";
  const image = (data.image || data.imageUrl || "").trim();
  const siteName = data.siteName || "";

  const twitterHandle = data.twitterHandle
    ? data.twitterHandle.startsWith("@")
      ? data.twitterHandle
      : `@${data.twitterHandle}`
    : null;

  const header = attributionUrl
    ? `// Generated by OmniSEO Tools (${attributionUrl})\n`
    : "";

  return `${header}import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${escapeTs(title)}',
  description: '${escapeTs(description)}',${url ? `\n  metadataBase: new URL('${escapeTs(url)}'),\n  alternates: {\n    canonical: '${escapeTs(url)}',\n  },` : ""}
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: '${escapeTs(title)}',
    description: '${escapeTs(description)}',${url ? `\n    url: '${escapeTs(url)}',` : ""}${siteName ? `\n    siteName: '${escapeTs(siteName)}',` : ""}${image ? `\n    images: [\n      {\n        url: '${escapeTs(image)}',\n        width: 1200,\n        height: 630,\n        alt: '${escapeTs(title)}',\n      },\n    ],` : ""}
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: '${escapeTs(title)}',
    description: '${escapeTs(description)}',${image ? `\n    images: ['${escapeTs(image)}'],` : ""}${twitterHandle ? `\n    site: '${escapeTs(twitterHandle)}',\n    creator: '${escapeTs(twitterHandle)}',` : ""}
  },
};`;
}

/**
 * Formats meta tags into a production-ready Shopify Theme Liquid template snippet.
 */
export function toLiquidSnippet(
  data: MetaFormData,
  attributionUrlOrOptions?: FormatterOptions
): string {
  const attributionUrl = resolveAttributionUrl(data, attributionUrlOrOptions);
  const twitterHandle = data.twitterHandle
    ? data.twitterHandle.startsWith("@")
      ? data.twitterHandle
      : `@${data.twitterHandle}`
    : null;

  const header = attributionUrl
    ? `{% comment %} Generated by OmniSEO Tools (${attributionUrl}) {% endcomment %}\n`
    : "";

  return `${header}{%- comment -%}
  Shopify Theme SEO & Social Meta Tags
  Snippet location: snippets/meta-tags.liquid
{%- endcomment -%}

<title>
  {{ page_title }}{% if current_tags %} &ndash; tagged "{{ current_tags | join: ', ' }}"{% endif %}{% if current_page != 1 %} &ndash; Page {{ current_page }}{% endif %}{% unless page_title contains shop.name %} &ndash; {{ shop.name }}{% endunless %}
</title>

{%- if page_description -%}
  <meta name="description" content="{{ page_description | escape }}">
{%- endif -%}

<link rel="canonical" href="{{ canonical_url }}">
<meta name="robots" content="index, follow">

<!-- Open Graph / Facebook -->
<meta property="og:site_name" content="{{ shop.name | escape }}">
<meta property="og:url" content="{{ canonical_url }}">
<meta property="og:title" content="{{ page_title | default: shop.name | escape }}">
<meta property="og:type" content="{% if request.page_type == 'product' %}product{% elsif request.page_type == 'article' %}article{% else %}website{% endif %}">
<meta property="og:description" content="{{ page_description | default: shop.description | escape }}">
{%- if page_image -%}
  <meta property="og:image" content="https:{{ page_image | image_url: width: 1200, height: 630 }}">
  <meta property="og:image:secure_url" content="https:{{ page_image | image_url: width: 1200, height: 630 }}">
{%- endif -%}

<!-- Twitter / X -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{{ page_title | default: shop.name | escape }}">
<meta name="twitter:description" content="{{ page_description | default: shop.description | escape }}">
{%- if page_image -%}
  <meta name="twitter:image" content="https:{{ page_image | image_url: width: 1200, height: 630 }}">
{%- endif -%}${twitterHandle ? `\n<meta name="twitter:site" content="${escapeHtml(twitterHandle)}">\n<meta name="twitter:creator" content="${escapeHtml(twitterHandle)}">` : ""}`;
}
